### ISSUE TITLE
Errors when running ./repl

### ISSUE THREAD

**Issue by Eyesonly88** [expo/project-repl#1]
Getting the following error when trying to run `./repl`:

```
> (node:53950) UnhandledPromiseRejectionWarning: Error: Cannot find module '@babel/runtime'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Requirer.require [as _require] ([eval]:1:37)
    at Requirer.requireAsync (MYAPP/node_modules/project-repl/index.js:222:22)
    at <anonymous>
(node:53950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53950) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cabe56** [comment]
Made a clean install with the following versions:
- node 13.12.0
- yarn 1.22.4
- npx 6.14.4

Got the following error when running `./repl`
```
> (node:74660) UnhandledPromiseRejectionWarning: /Users/josevarela/Repositories/testing-cuanto/node_modules/expo/build/Expo.fx.js:1
import './environment/muteWarnings.fx';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/josevarela/Repositories/testing-cuanto/node_modules/expo/build/ExpoLazy.js:476:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
(node:74660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
